### ISSUE TITLE
Directory Structure, IPC Using UNIX Domain Sockets

### ISSUE THREAD

**Issue by rye** [frc2503/rdeploy#1]
Since `rdeploy` will be both a server and a command-line, we need to have the ability for each repository, when it is pushed to, to run its `post-receive` hook and send some kind of event to the server.

UNIX Domain Sockets are probably the best way of doing this.

When we spawn up a server, we should create a Temporary Directory (in `/tmp/`) to hold our data.  The path will probably look something like `/tmp/rdeploy-26183.ae71f8/`.

Inside of this, we will create a `sock` file, which is what the UNIX Domain Socket Server will connect to.  We will also have all of the git repositories in subdirectories named `{name}.git/`.

**Comment by rye** [comment]
After thinking about this, I've changed my mind.  We should just have a `/tmp/rdeploy-{pid}.sock` socket file for connecting to.  This will make things quite a bit simpler, as we can then just tell RDeploy to bootstrap itself in existing directories.

**Comment by rye** [comment]
Each repository should have a `.rdeploy.yml` configuration file in its root, and that'll contain the important configuration information for it.

```yaml
project:
  name: "r2015" # A short operator, unique to this project.
  title: "2015 Robot Code" # A display title.
  description: "The code for the 2015 robot." # A display description of the project.

deploy: "ant deploy" # required: command to compile and deploy the code.

targets: # in order of precedence; RDeploy will ping each in sequence, and, if one responds, RDeploy will attempt to deploy there. If it fails, it'll resume pinging each in sequence.
  - "roboRIO-2503.local"
  - "10.25.3.7"
```
